USE TheGoodTasteDB;
GO

CREATE TABLE Productos(
	IdProducto INT IDENTITY(1,1) PRIMARY KEY,
	Codigo VARCHAR(50) NOT NULL UNIQUE,
	Nombre VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(250) NULL,
	Precio DECIMAL(18,2) NOT NULL,
	Stock INT NOT NULL,
	StockMinimo INT NOT NULL,
	IdCategoria INT NOT NULL,
	CreateAt DATETIME DEFAULT GETDATE(),
	DeleteAt DATETIME NULL
);
GO